// lib/catalogo-oficial-dados.ts
// Base de dados padronizada oficial (ANVISA / CMED / RENAME / CATMAT) para SGH

export interface ItemCatalogoOficial {
  tipoItem: 'MEDICAMENTO' | 'MATERIAL';
  nome: string;
  principioAtivo: string;
  forma?: string;
  concentracao?: string;
  unidade?: string;
  codigoEan?: string;
  codigoAnvisa?: string; // Código ANVISA para medicamentos ou Código CATMAT para materiais
  classeTerapeutica?: string;
  viaAdministracao?: string;
  mav?: boolean;
  duplaChecagem?: boolean;
  tipoControle?: string;
  estoqueMinimoSugerido?: number;
  sinonimos?: string[]; // Marcas comerciais, nomes populares ou termos de busca
}

export const CATALOGO_OFICIAL_COMPLETO: ItemCatalogoOficial[] = [
  // =========================================================================
  // 1. ANALGÉSICOS, ANTIPIRÉTICOS E ANTI-INFLAMATÓRIOS (AINEs e OPIOIDES)
  // =========================================================================
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Dipirona Sódica 500mg/mL Injetável (2mL)',
    principioAtivo: 'Dipirona Monoidratada',
    forma: 'Solução Injetável',
    concentracao: '500 mg/mL (2 mL)',
    unidade: 'AMP',
    codigoEan: '7891058001234',
    codigoAnvisa: '1018100230012',
    classeTerapeutica: 'Analgésico e Antipirético',
    viaAdministracao: 'INTRAVENOSA',
    estoqueMinimoSugerido: 100,
    sinonimos: ['Novalgina', 'Anador', 'Dipidor', 'Magnopyrol', 'Difebril', 'Maxiliv', 'Termopirona'],
  },
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Dipirona Sódica 500mg Comprimido',
    principioAtivo: 'Dipirona Monoidratada',
    forma: 'Comprimido',
    concentracao: '500 mg',
    unidade: 'COMP',
    codigoEan: '7891058001241',
    codigoAnvisa: '1018100230020',
    classeTerapeutica: 'Analgésico e Antipirético',
    viaAdministracao: 'ORAL',
    estoqueMinimoSugerido: 200,
    sinonimos: ['Novalgina 500mg', 'Anador 500mg', 'Dipidor Comp'],
  },
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Paracetamol 500mg Comprimido',
    principioAtivo: 'Paracetamol',
    forma: 'Comprimido',
    concentracao: '500 mg',
    unidade: 'COMP',
    codigoEan: '7891058001258',
    codigoAnvisa: '1018100340015',
    classeTerapeutica: 'Analgésico e Antipirético',
    viaAdministracao: 'ORAL',
    estoqueMinimoSugerido: 150,
    sinonimos: ['Tylenol', 'Parador', 'Pacemol', 'Dôrico', 'Tylaflex'],
  },
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Paracetamol 200mg/mL Gotas (15mL)',
    principioAtivo: 'Paracetamol',
    forma: 'Solução Oral Gotas',
    concentracao: '200 mg/mL',
    unidade: 'FR',
    codigoEan: '7891058001265',
    codigoAnvisa: '1018100340023',
    classeTerapeutica: 'Analgésico e Antipirético Pediátrico',
    viaAdministracao: 'ORAL',
    estoqueMinimoSugerido: 30,
    sinonimos: ['Tylenol Bebê', 'Tylenol Gotas', 'Paracetamol Gotas'],
  },
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Cetoprofeno 100mg Pó Liofilizado IV',
    principioAtivo: 'Cetoprofeno',
    forma: 'Pó Liofilizado Injetável',
    concentracao: '100 mg',
    unidade: 'FR/AMP',
    codigoEan: '7891058001272',
    codigoAnvisa: '1018100450018',
    classeTerapeutica: 'Anti-inflamatório Não Esteroidal (AINE)',
    viaAdministracao: 'INTRAVENOSA',
    estoqueMinimoSugerido: 80,
    sinonimos: ['Profenid IV', 'Ketoprofeno IV', 'Artrosil IV'],
  },
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Cetoprofeno 100mg/2mL Injetável IM',
    principioAtivo: 'Cetoprofeno',
    forma: 'Solução Injetável',
    concentracao: '100 mg/2 mL',
    unidade: 'AMP',
    codigoEan: '7891058001289',
    codigoAnvisa: '1018100450026',
    classeTerapeutica: 'Anti-inflamatório Não Esteroidal (AINE)',
    viaAdministracao: 'INTRAMUSCULAR',
    estoqueMinimoSugerido: 60,
    sinonimos: ['Profenid IM', 'Ketoprofeno IM'],
  },
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Tenoxicam 20mg Pó para Injetável',
    principioAtivo: 'Tenoxicam',
    forma: 'Pó Liofilizado Injetável + Diluente',
    concentracao: '20 mg',
    unidade: 'FR/AMP',
    codigoEan: '7891058001296',
    codigoAnvisa: '1018100560010',
    classeTerapeutica: 'Anti-inflamatório Não Esteroidal (AINE)',
    viaAdministracao: 'INTRAVENOSA',
    estoqueMinimoSugerido: 40,
    sinonimos: ['Tilatil', 'Tenoftal', 'Teflan'],
  },
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Diclofenaco Sódico 75mg/3mL Injetável',
    principioAtivo: 'Diclofenaco Sódico',
    forma: 'Solução Injetável',
    concentracao: '75 mg/3 mL',
    unidade: 'AMP',
    codigoEan: '7891058001302',
    codigoAnvisa: '1018100670013',
    classeTerapeutica: 'Anti-inflamatório e Analgésico',
    viaAdministracao: 'INTRAMUSCULAR',
    estoqueMinimoSugerido: 60,
    sinonimos: ['Voltaren', 'Voltaren IM', 'Artren', 'Biofenac'],
  },
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Morfina 10mg/mL Injetável (1mL)',
    principioAtivo: 'Sulfato de Morfina',
    forma: 'Solução Injetável',
    concentracao: '10 mg/mL',
    unidade: 'AMP',
    codigoEan: '7891058001319',
    codigoAnvisa: '1018100780016',
    classeTerapeutica: 'Analgésico Opioide Forte',
    viaAdministracao: 'INTRAVENOSA',
    mav: true,
    duplaChecagem: true,
    tipoControle: 'Portaria 344 - Lista A1 (Entorpecentes)',
    estoqueMinimoSugerido: 20,
    sinonimos: ['Dimorf', 'Dimorf 10mg', 'Morfina Sulfato'],
  },
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Fentanila 50mcg/mL Injetável (2mL)',
    principioAtivo: 'Citrato de Fentanila',
    forma: 'Solução Injetável',
    concentracao: '50 mcg/mL (2 mL)',
    unidade: 'AMP',
    codigoEan: '7891058001326',
    codigoAnvisa: '1018100890019',
    classeTerapeutica: 'Analgésico Opioide / Anestésico',
    viaAdministracao: 'INTRAVENOSA',
    mav: true,
    duplaChecagem: true,
    tipoControle: 'Portaria 344 - Lista A1 (Entorpecentes)',
    estoqueMinimoSugerido: 30,
    sinonimos: ['Fentanil', 'Fentanyl', 'Unifental', 'Fentanest'],
  },
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Tramadol 50mg/mL Injetável (1mL)',
    principioAtivo: 'Cloridrato de Tramadol',
    forma: 'Solução Injetável',
    concentracao: '50 mg/mL',
    unidade: 'AMP',
    codigoEan: '7891058001333',
    codigoAnvisa: '1018100900011',
    classeTerapeutica: 'Analgésico Opioide Moderado',
    viaAdministracao: 'INTRAVENOSA',
    tipoControle: 'Portaria 344 - Lista A2 (Opioides)',
    estoqueMinimoSugerido: 40,
    sinonimos: ['Tramal', 'Dorless', 'Tramadon', 'Sylador'],
  },

  // =========================================================================
  // 2. GASTROENTEROLOGIA & ANTIEMÉTICOS
  // =========================================================================
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Metoclopramida 10mg/2mL Injetável',
    principioAtivo: 'Cloridrato de Metoclopramida',
    forma: 'Solução Injetável',
    concentracao: '10 mg/2 mL',
    unidade: 'AMP',
    codigoEan: '7891058001340',
    codigoAnvisa: '1018101010014',
    classeTerapeutica: 'Antiemético e Procinético Gastrointestinal',
    viaAdministracao: 'INTRAVENOSA',
    estoqueMinimoSugerido: 80,
    sinonimos: ['Plasil', 'Eucil', 'Noprosil', 'Plamet'],
  },
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Ondansetrona 4mg/2mL Injetável IV',
    principioAtivo: 'Cloridrato de Ondansetrona',
    forma: 'Solução Injetável',
    concentracao: '4 mg/2 mL',
    unidade: 'AMP',
    codigoEan: '7891058001357',
    codigoAnvisa: '1018101120017',
    classeTerapeutica: 'Antiemético / Antagonista 5-HT3',
    viaAdministracao: 'INTRAVENOSA',
    estoqueMinimoSugerido: 60,
    sinonimos: ['Vonau Flash', 'Zofran', 'Nausedron', 'Ondantril'],
  },
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Ondansetrona 8mg Comprimido Orodispersível',
    principioAtivo: 'Cloridrato de Ondansetrona',
    forma: 'Comprimido Orodispersível',
    concentracao: '8 mg',
    unidade: 'COMP',
    codigoEan: '7891058001364',
    codigoAnvisa: '1018101120025',
    classeTerapeutica: 'Antiemético',
    viaAdministracao: 'ORAL',
    estoqueMinimoSugerido: 40,
    sinonimos: ['Vonau Flash 8mg', 'Zofran 8mg'],
  },
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Dimenidrinato + Piridoxina 50mg/mL Injetável',
    principioAtivo: 'Dimenidrinato + Cloridrato de Piridoxina',
    forma: 'Solução Injetável',
    concentracao: '50 mg + 50 mg / mL',
    unidade: 'AMP',
    codigoEan: '7891058001371',
    codigoAnvisa: '1018101230010',
    classeTerapeutica: 'Antiemético e Antivertiginoso',
    viaAdministracao: 'INTRAVENOSA',
    estoqueMinimoSugerido: 50,
    sinonimos: ['Dramin B6', 'Dramin B6 Injetável', 'Dramavit B6'],
  },
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Butilbrometo de Escopolamina + Dipirona 5mL',
    principioAtivo: 'Butilbrometo de Escopolamina + Dipirona',
    forma: 'Solução Injetável',
    concentracao: '4 mg + 500 mg / 5 mL',
    unidade: 'AMP',
    codigoEan: '7891058001388',
    codigoAnvisa: '1018101340012',
    classeTerapeutica: 'Antiespasmódico e Analgésico',
    viaAdministracao: 'INTRAVENOSA',
    estoqueMinimoSugerido: 80,
    sinonimos: ['Buscopan Composto', 'Buscopan Plus', 'Hioscina Composta', 'Tropinal'],
  },
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Omeprazol 40mg Pó para Injetável',
    principioAtivo: 'Omeprazol Sódico',
    forma: 'Pó Liofilizado Injetável + Diluente',
    concentracao: '40 mg',
    unidade: 'FR/AMP',
    codigoEan: '7891058001395',
    codigoAnvisa: '1018101450015',
    classeTerapeutica: 'Inibidor da Bomba de Prótons (IBP)',
    viaAdministracao: 'INTRAVENOSA',
    estoqueMinimoSugerido: 90,
    sinonimos: ['Losec IV', 'Peprazol IV', 'Gaspiren IV', 'Omeprotec'],
  },
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Pantoprazol 40mg Pó para Injetável',
    principioAtivo: 'Pantoprazol Sódico',
    forma: 'Pó Liofilizado Injetável',
    concentracao: '40 mg',
    unidade: 'FR/AMP',
    codigoEan: '7891058001401',
    codigoAnvisa: '1018101560018',
    classeTerapeutica: 'Inibidor da Bomba de Prótons (IBP)',
    viaAdministracao: 'INTRAVENOSA',
    estoqueMinimoSugerido: 50,
    sinonimos: ['Pantozol IV', 'Pripanto IV', 'Pantocal IV'],
  },

  // =========================================================================
  // 3. ANTIBIÓTICOS E ANTIMICROBIANOS
  // =========================================================================
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Ceftriaxona Dissódica 1g Pó para Injetável IV',
    principioAtivo: 'Ceftriaxona Dissódica',
    forma: 'Pó Liofilizado Injetável + Diluente',
    concentracao: '1 g',
    unidade: 'FR/AMP',
    codigoEan: '7891058001418',
    codigoAnvisa: '1018101670010',
    classeTerapeutica: 'Antibiótico Cefalosporina de 3ª Geração',
    viaAdministracao: 'INTRAVENOSA',
    tipoControle: 'RDC 20/2011 - Antimicrobianos (Receita em 2 Vias)',
    estoqueMinimoSugerido: 70,
    sinonimos: ['Rocefin', 'Rocephin', 'Triaxin', 'Ceftriax', 'Keftron'],
  },
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Amoxicilina + Clavulanato de Potássio 1g+200mg IV',
    principioAtivo: 'Amoxicilina + Clavulanato de Potássio',
    forma: 'Pó para Solução Injetável',
    concentracao: '1000 mg + 200 mg',
    unidade: 'FR/AMP',
    codigoEan: '7891058001425',
    codigoAnvisa: '1018101780013',
    classeTerapeutica: 'Antibiótico Penicilínico + Inibidor de Beta-Lactamase',
    viaAdministracao: 'INTRAVENOSA',
    tipoControle: 'RDC 20/2011 - Antimicrobianos',
    estoqueMinimoSugerido: 40,
    sinonimos: ['Clavulin IV', 'Novamox IV', 'Amoxiclav IV', 'Policlav'],
  },
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Ciprofloxacino 200mg/100mL Bolsa Infusão',
    principioAtivo: 'Cloridrato de Ciprofloxacino',
    forma: 'Solução para Infusão em Bolsa',
    concentracao: '2 mg/mL (100 mL)',
    unidade: 'BOLSA',
    codigoEan: '7891058001432',
    codigoAnvisa: '1018101890016',
    classeTerapeutica: 'Antibiótico Fluoroquinolona',
    viaAdministracao: 'INTRAVENOSA',
    tipoControle: 'RDC 20/2011 - Antimicrobianos',
    estoqueMinimoSugerido: 30,
    sinonimos: ['Cipro IV', 'Ciprofloxacina Infusão', 'Quinoflox IV'],
  },
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Metronidazol 500mg/100mL Bolsa Infusão',
    principioAtivo: 'Metronidazol',
    forma: 'Solução para Infusão em Bolsa',
    concentracao: '5 mg/mL (100 mL)',
    unidade: 'BOLSA',
    codigoEan: '7891058001449',
    codigoAnvisa: '1018101900018',
    classeTerapeutica: 'Antimicrobiano / Anti-infeccioso Anaeróbio',
    viaAdministracao: 'INTRAVENOSA',
    tipoControle: 'RDC 20/2011 - Antimicrobianos',
    estoqueMinimoSugerido: 30,
    sinonimos: ['Flagyl IV', 'Metronidazol Infusão', 'Helmizol IV'],
  },
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Azitromicina 500mg Pó para Injetável',
    principioAtivo: 'Azitromicina Di-hidratada',
    forma: 'Pó Liofilizado Injetável',
    concentracao: '500 mg',
    unidade: 'FR/AMP',
    codigoEan: '7891058001456',
    codigoAnvisa: '1018102010011',
    classeTerapeutica: 'Antibiótico Macrolídeo',
    viaAdministracao: 'INTRAVENOSA',
    tipoControle: 'RDC 20/2011 - Antimicrobianos',
    estoqueMinimoSugerido: 25,
    sinonimos: ['Zithromax IV', 'Azi IV', 'Zitromil'],
  },
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Meropenem 1g Pó para Injetável IV',
    principioAtivo: 'Meropenem Tri-hidratado',
    forma: 'Pó para Solução Injetável',
    concentracao: '1 g',
    unidade: 'FR/AMP',
    codigoEan: '7891058001463',
    codigoAnvisa: '1018102120014',
    classeTerapeutica: 'Antibiótico Carbapenêmico de Amplo Espectro',
    viaAdministracao: 'INTRAVENOSA',
    mav: true,
    duplaChecagem: true,
    tipoControle: 'RDC 20/2011 - Antimicrobianos',
    estoqueMinimoSugerido: 20,
    sinonimos: ['Meronem', 'Mepem', 'Meropen', 'Merocid'],
  },
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Vancomicina 500mg Pó para Injetável IV',
    principioAtivo: 'Cloridrato de Vancomicina',
    forma: 'Pó Liofilizado Injetável',
    concentracao: '500 mg',
    unidade: 'FR/AMP',
    codigoEan: '7891058001470',
    codigoAnvisa: '1018102230017',
    classeTerapeutica: 'Antibiótico Glicopeptídeo',
    viaAdministracao: 'INTRAVENOSA',
    mav: true,
    duplaChecagem: true,
    tipoControle: 'RDC 20/2011 - Antimicrobianos',
    estoqueMinimoSugerido: 20,
    sinonimos: ['Vancocina', 'Vancocid', 'Novovancocin'],
  },

  // =========================================================================
  // 4. RESPIRATÓRIO, CORTICOIDES E ANTI-HISTAMÍNICOS
  // =========================================================================
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Hidrocortisona 500mg Pó para Injetável',
    principioAtivo: 'Succinato Sódico de Hidrocortisona',
    forma: 'Pó Liofilizado Injetável + Diluente',
    concentracao: '500 mg',
    unidade: 'FR/AMP',
    codigoEan: '7891058001487',
    codigoAnvisa: '1018102340019',
    classeTerapeutica: 'Glicocorticoide Sistêmico',
    viaAdministracao: 'INTRAVENOSA',
    estoqueMinimoSugerido: 60,
    sinonimos: ['Solu-Cortef', 'Flebocortid', 'Cortisona 500'],
  },
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Hidrocortisona 100mg Pó para Injetável',
    principioAtivo: 'Succinato Sódico de Hidrocortisona',
    forma: 'Pó Liofilizado Injetável + Diluente',
    concentracao: '100 mg',
    unidade: 'FR/AMP',
    codigoEan: '7891058001494',
    codigoAnvisa: '1018102340027',
    classeTerapeutica: 'Glicocorticoide Sistêmico',
    viaAdministracao: 'INTRAVENOSA',
    estoqueMinimoSugerido: 50,
    sinonimos: ['Solu-Cortef 100mg', 'Cortisona 100'],
  },
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Dexametasona 4mg/mL Injetável (2,5mL)',
    principioAtivo: 'Fosfato Dissódico de Dexametasona',
    forma: 'Solução Injetável',
    concentracao: '4 mg/mL (10 mg/2,5 mL)',
    unidade: 'FR/AMP',
    codigoEan: '7891058001500',
    codigoAnvisa: '1018102450012',
    classeTerapeutica: 'Glicocorticoide Potente',
    viaAdministracao: 'INTRAVENOSA',
    estoqueMinimoSugerido: 60,
    sinonimos: ['Decadron', 'Dexamex', 'Dexametasona Injetável', 'Koidexa'],
  },
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Sulfato de Salbutamol 5mg/mL Solução para Nebulização',
    principioAtivo: 'Sulfato de Salbutamol',
    forma: 'Solução para Inalação / Gotas',
    concentracao: '5 mg/mL (10 mL)',
    unidade: 'FR',
    codigoEan: '7891058001517',
    codigoAnvisa: '1018102560015',
    classeTerapeutica: 'Broncodilatador Beta-2 Agonista',
    viaAdministracao: 'INALATORIA',
    estoqueMinimoSugerido: 20,
    sinonimos: ['Aerolin Gotas', 'Aerolin Nebulização', 'Salbutamol Gotas'],
  },
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Brometo de Ipratrópio 0,25mg/mL Solução Inalação',
    principioAtivo: 'Brometo de Ipratrópio',
    forma: 'Solução para Inalação / Gotas',
    concentracao: '0,25 mg/mL (20 mL)',
    unidade: 'FR',
    codigoEan: '7891058001524',
    codigoAnvisa: '1018102670018',
    classeTerapeutica: 'Broncodilatador Anticolinérgico',
    viaAdministracao: 'INALATORIA',
    estoqueMinimoSugerido: 20,
    sinonimos: ['Atrovent', 'Atrovent Gotas', 'Ipratrópio Gotas'],
  },
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Prometazina 25mg/mL Injetável (2mL)',
    principioAtivo: 'Cloridrato de Prometazina',
    forma: 'Solução Injetável',
    concentracao: '25 mg/mL (50 mg/2 mL)',
    unidade: 'AMP',
    codigoEan: '7891058001531',
    codigoAnvisa: '1018102780010',
    classeTerapeutica: 'Anti-histamínico H1 e Sedativo',
    viaAdministracao: 'INTRAMUSCULAR',
    estoqueMinimoSugerido: 50,
    sinonimos: ['Fenergan', 'Fenergan IM', 'Profergan'],
  },

  // =========================================================================
  // 5. CARDIOVASCULAR, URGÊNCIA, ELETRÓLITOS E SOLUÇÕES
  // =========================================================================
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Noraepinefrina (Norepinefrina) 2mg/mL (4mL)',
    principioAtivo: 'Hemitartarato de Norepinefrina',
    forma: 'Solução Injetável Concentrada',
    concentracao: '2 mg/mL (8 mg/4 mL)',
    unidade: 'AMP',
    codigoEan: '7891058001548',
    codigoAnvisa: '1018102890013',
    classeTerapeutica: 'Vasopressor / Amina Vasoativa',
    viaAdministracao: 'INTRAVENOSA',
    mav: true,
    duplaChecagem: true,
    estoqueMinimoSugerido: 30,
    sinonimos: ['Noradrenalina', 'Nora', 'Levophed', 'Norepina'],
  },
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Adrenalina (Epinefrina) 1mg/mL Injetável (1mL)',
    principioAtivo: 'Epinefrina',
    forma: 'Solução Injetável',
    concentracao: '1 mg/mL',
    unidade: 'AMP',
    codigoEan: '7891058001555',
    codigoAnvisa: '1018102900015',
    classeTerapeutica: 'Vasopressor / Parada Cardiorrespiratória',
    viaAdministracao: 'INTRAVENOSA',
    mav: true,
    duplaChecagem: true,
    estoqueMinimoSugerido: 40,
    sinonimos: ['Adrenalina 1:1000', 'Epinefrina Injetável', 'Epi 1mg'],
  },
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Amiodarona 50mg/mL Injetável (3mL)',
    principioAtivo: 'Cloridrato de Amiodarona',
    forma: 'Solução Injetável',
    concentracao: '50 mg/mL (150 mg/3 mL)',
    unidade: 'AMP',
    codigoEan: '7891058001562',
    codigoAnvisa: '1018103010018',
    classeTerapeutica: 'Antiarrítmico Classe III',
    viaAdministracao: 'INTRAVENOSA',
    mav: true,
    duplaChecagem: true,
    estoqueMinimoSugerido: 30,
    sinonimos: ['Ancoron IV', 'Atlansil IV', 'Amiodar'],
  },
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Furosemida 10mg/mL Injetável (2mL)',
    principioAtivo: 'Furosemida',
    forma: 'Solução Injetável',
    concentracao: '10 mg/mL (20 mg/2 mL)',
    unidade: 'AMP',
    codigoEan: '7891058001579',
    codigoAnvisa: '1018103120010',
    classeTerapeutica: 'Diurético de Alça',
    viaAdministracao: 'INTRAVENOSA',
    estoqueMinimoSugerido: 60,
    sinonimos: ['Lasix IV', 'Furosemida Injetável', 'Uripax'],
  },
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Cloreto de Sódio 0,9% Bolsa 500mL',
    principioAtivo: 'Cloreto de Sódio 0,9%',
    forma: 'Solução Fisiológica para Infusão',
    concentracao: '0,9% (0,9g/100mL)',
    unidade: 'FR/BOLSA',
    codigoEan: '7891058001586',
    codigoAnvisa: '1018103230013',
    classeTerapeutica: 'Solução Hidroeletrolítica Isotônica',
    viaAdministracao: 'INTRAVENOSA',
    estoqueMinimoSugerido: 150,
    sinonimos: ['Soro Fisiológico 0,9%', 'SF 0,9% 500mL', 'NaCl 0,9%'],
  },
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Cloreto de Sódio 0,9% Bolsa 100mL',
    principioAtivo: 'Cloridrato de Sódio 0,9%',
    forma: 'Solução Fisiológica para Infusão',
    concentracao: '0,9% (100 mL)',
    unidade: 'FR/BOLSA',
    codigoEan: '7891058001593',
    codigoAnvisa: '1018103230021',
    classeTerapeutica: 'Solução Hidroeletrolítica Diluente',
    viaAdministracao: 'INTRAVENOSA',
    estoqueMinimoSugerido: 100,
    sinonimos: ['SF 0,9% 100mL', 'Soro 100mL para diluição'],
  },
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Glicose 5% Bolsa 500mL',
    principioAtivo: 'Glicose Monoidratada',
    forma: 'Solução Glicosada Isotônica',
    concentracao: '5% (500 mL)',
    unidade: 'FR/BOLSA',
    codigoEan: '7891058001609',
    codigoAnvisa: '1018103340016',
    classeTerapeutica: 'Solução Glicosada para Infusão',
    viaAdministracao: 'INTRAVENOSA',
    estoqueMinimoSugerido: 80,
    sinonimos: ['Soro Glicosado 5%', 'SG 5% 500mL'],
  },
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Ringer com Lactato Bolsa 500mL',
    principioAtivo: 'Cloreto de Sódio + Potássio + Cálcio + Lactato de Sódio',
    forma: 'Solução Eletrolítica Balanceada',
    concentracao: '500 mL',
    unidade: 'FR/BOLSA',
    codigoEan: '7891058001616',
    codigoAnvisa: '1018103450019',
    classeTerapeutica: 'Expansor Volêmico / Solução Balanceada',
    viaAdministracao: 'INTRAVENOSA',
    estoqueMinimoSugerido: 80,
    sinonimos: ['Ringer Lactato', 'RL 500mL', 'Soro Ringer'],
  },
  {
    tipoItem: 'MEDICAMENTO',
    nome: 'Glicose 50% Injetável Hipertônica (10mL)',
    principioAtivo: 'Glicose 50%',
    forma: 'Solução Hipertônica Injetável',
    concentracao: '50% (10 mL)',
    unidade: 'AMP',
    codigoEan: '7891058001623',
    codigoAnvisa: '1018103560011',
    classeTerapeutica: 'Reposição Glicêmica Rápida / Hipoglicemia',
    viaAdministracao: 'INTRAVENOSA',
    mav: true,
    duplaChecagem: true,
    estoqueMinimoSugerido: 50,
    sinonimos: ['Glicose 50%', 'G50%', 'Glicose Hipertônica'],
  },

  // =========================================================================
  // 6. MATERIAIS MÉDICO-HOSPITALARES PADRÃO CATMAT (Compras.gov.br)
  // =========================================================================
  {
    tipoItem: 'MATERIAL',
    nome: 'Cateter Intravenoso Periférico 20G com Dispositivo de Segurança',
    principioAtivo: 'Cateter Venoso Periférico em Poliuretano / Teflon',
    forma: 'Dispositivo Estéril Descartável',
    concentracao: 'Calibre 20G (Rosa)',
    unidade: 'UNID',
    codigoEan: '7891058002019',
    codigoAnvisa: 'CATMAT-445821',
    classeTerapeutica: 'Acesso Vascular / Material Hospitalar',
    estoqueMinimoSugerido: 100,
    sinonimos: ['Abocath 20G', 'Jelco 20G', 'Cateter Rosa', 'Punção Venosa 20G', 'Acesso 20'],
  },
  {
    tipoItem: 'MATERIAL',
    nome: 'Cateter Intravenoso Periférico 22G com Dispositivo de Segurança',
    principioAtivo: 'Cateter Venoso Periférico em Poliuretano',
    forma: 'Dispositivo Estéril Descartável',
    concentracao: 'Calibre 22G (Azul)',
    unidade: 'UNID',
    codigoEan: '7891058002026',
    codigoAnvisa: 'CATMAT-445822',
    classeTerapeutica: 'Acesso Vascular / Material Hospitalar',
    estoqueMinimoSugerido: 100,
    sinonimos: ['Abocath 22G', 'Jelco 22G', 'Cateter Azul', 'Punção Venosa 22G'],
  },
  {
    tipoItem: 'MATERIAL',
    nome: 'Cateter Intravenoso Periférico 18G com Dispositivo de Segurança',
    principioAtivo: 'Cateter Venoso Periférico',
    forma: 'Dispositivo Estéril Descartável',
    concentracao: 'Calibre 18G (Verde)',
    unidade: 'UNID',
    codigoEan: '7891058002033',
    codigoAnvisa: 'CATMAT-445820',
    classeTerapeutica: 'Acesso Vascular / Trauma e Hemotransfusão',
    estoqueMinimoSugerido: 60,
    sinonimos: ['Abocath 18G', 'Jelco 18G', 'Cateter Verde 18'],
  },
  {
    tipoItem: 'MATERIAL',
    nome: 'Seringa Hipodérmica Descartável 20mL Luer Lock sem Agulha',
    principioAtivo: 'Polipropileno Transparente com Êmbolo Siliconizado',
    forma: 'Seringa Descartável Estéril',
    concentracao: '20 mL',
    unidade: 'UNID',
    codigoEan: '7891058002040',
    codigoAnvisa: 'CATMAT-398214',
    classeTerapeutica: 'Administração de Medicamentos e Aspiração',
    estoqueMinimoSugerido: 150,
    sinonimos: ['Seringa 20mL', 'Seringa 20cc', 'Seringa Rosca Luer Lock 20mL'],
  },
  {
    tipoItem: 'MATERIAL',
    nome: 'Seringa Hipodérmica Descartável 10mL Luer Lock sem Agulha',
    principioAtivo: 'Polipropileno Transparente com Êmbolo Siliconizado',
    forma: 'Seringa Descartável Estéril',
    concentracao: '10 mL',
    unidade: 'UNID',
    codigoEan: '7891058002057',
    codigoAnvisa: 'CATMAT-398213',
    classeTerapeutica: 'Administração de Medicamentos',
    estoqueMinimoSugerido: 200,
    sinonimos: ['Seringa 10mL', 'Seringa 10cc', 'Seringa Luer Lock 10mL'],
  },
  {
    tipoItem: 'MATERIAL',
    nome: 'Seringa Hipodérmica Descartável 5mL Luer Slip sem Agulha',
    principioAtivo: 'Polipropileno Transparente',
    forma: 'Seringa Descartável Estéril',
    concentracao: '5 mL',
    unidade: 'UNID',
    codigoEan: '7891058002064',
    codigoAnvisa: 'CATMAT-398212',
    classeTerapeutica: 'Administração de Medicamentos',
    estoqueMinimoSugerido: 200,
    sinonimos: ['Seringa 5mL', 'Seringa 5cc'],
  },
  {
    tipoItem: 'MATERIAL',
    nome: 'Seringa Descartável para Insulina 1mL com Agulha Fixa 13x0,45mm',
    principioAtivo: 'Seringa 100 UI com Agulha Ultrafina',
    forma: 'Seringa Descartável Estéril',
    concentracao: '1 mL (100 UI)',
    unidade: 'UNID',
    codigoEan: '7891058002071',
    codigoAnvisa: 'CATMAT-398210',
    classeTerapeutica: 'Aplicação Subcutânea de Insulina / Heparina',
    estoqueMinimoSugerido: 100,
    sinonimos: ['Seringa de Insulina', 'Seringa 1mL Insulina', 'Seringa 100UI'],
  },
  {
    tipoItem: 'MATERIAL',
    nome: 'Agulha Hipodérmica Descartável 40x1,2mm (Rosa - Aspiração)',
    principioAtivo: 'Aço Inoxidável Siliconizado com Conexão Luer',
    forma: 'Agulha Descartável Estéril',
    concentracao: '40 x 1,2 mm (18G)',
    unidade: 'UNID',
    codigoEan: '7891058002088',
    codigoAnvisa: 'CATMAT-412389',
    classeTerapeutica: 'Aspiração e Preparo de Medicamentos',
    estoqueMinimoSugerido: 300,
    sinonimos: ['Agulha 40x12', 'Agulha Rosa', 'Agulha de Aspiração', 'Agulha 18G'],
  },
  {
    tipoItem: 'MATERIAL',
    nome: 'Agulha Hipodérmica Descartável 25x0,7mm (Preta - Aplicação IM/IV)',
    principioAtivo: 'Aço Inoxidável Siliconizado',
    forma: 'Agulha Descartável Estéril',
    concentracao: '25 x 0,7 mm (22G)',
    unidade: 'UNID',
    codigoEan: '7891058002095',
    codigoAnvisa: 'CATMAT-412390',
    classeTerapeutica: 'Aplicação Intramuscular e Endovenosa',
    estoqueMinimoSugerido: 250,
    sinonimos: ['Agulha 25x7', 'Agulha Preta', 'Agulha IM Adulto', 'Agulha 22G'],
  },
  {
    tipoItem: 'MATERIAL',
    nome: 'Agulha Hipodérmica Descartável 13x0,45mm (Marrom - Subcutânea)',
    principioAtivo: 'Aço Inoxidável Siliconizado',
    forma: 'Agulha Descartável Estéril',
    concentracao: '13 x 0,45 mm (26G)',
    unidade: 'UNID',
    codigoEan: '7891058002101',
    codigoAnvisa: 'CATMAT-412391',
    classeTerapeutica: 'Aplicação Subcutânea e Intradérmica',
    estoqueMinimoSugerido: 200,
    sinonimos: ['Agulha 13x4,5', 'Agulha Marrom', 'Agulha SC', 'Agulha 26G'],
  },
  {
    tipoItem: 'MATERIAL',
    nome: 'Equipo Macrogotas para Infusão Gravitacional com Injetor Lateral',
    principioAtivo: 'Equipo de Infusão Parenteral em PVC Flexível',
    forma: 'Equipo Descartável Estéril',
    concentracao: '20 gotas = 1 mL',
    unidade: 'UNID',
    codigoEan: '7891058002118',
    codigoAnvisa: 'CATMAT-356190',
    classeTerapeutica: 'Infusão Venosa Gravitacional',
    estoqueMinimoSugerido: 150,
    sinonimos: ['Equipo Macrogotas', 'Equipo de Soro', 'Equipo Simples', 'Equipo Gravitacional'],
  },
  {
    tipoItem: 'MATERIAL',
    nome: 'Equipo Fotoprotetor para Bomba de Infusão Contínua',
    principioAtivo: 'Equipo em PVC Âmbar com Proteção UV',
    forma: 'Equipo Descartável Estéril',
    concentracao: 'Via Fotoprotetora (Nitroprussiato, etc)',
    unidade: 'UNID',
    codigoEan: '7891058002125',
    codigoAnvisa: 'CATMAT-356195',
    classeTerapeutica: 'Infusão de Medicamentos Fotossensíveis',
    estoqueMinimoSugerido: 30,
    sinonimos: ['Equipo Âmbar', 'Equipo Fotossensível', 'Equipo Escuro'],
  },
  {
    tipoItem: 'MATERIAL',
    nome: 'Luva de Procedimento Não Cirúrgica em Látex Tamanho M (Caixa c/ 100)',
    principioAtivo: 'Látex Natural com Pó Bioabsorvível',
    forma: 'Luva de Procedimento Ambidestra',
    concentracao: 'Tamanho M',
    unidade: 'CX',
    codigoEan: '7891058002132',
    codigoAnvisa: 'CATMAT-289410',
    classeTerapeutica: 'Equipamento de Proteção Individual (EPI)',
    estoqueMinimoSugerido: 20,
    sinonimos: ['Luva de Procedimento M', 'Luva Látex M', 'Luva Descartável M'],
  },
  {
    tipoItem: 'MATERIAL',
    nome: 'Luva de Procedimento Não Cirúrgica em Látex Tamanho G (Caixa c/ 100)',
    principioAtivo: 'Látex Natural com Pó Bioabsorvível',
    forma: 'Luva de Procedimento Ambidestra',
    concentracao: 'Tamanho G',
    unidade: 'CX',
    codigoEan: '7891058002149',
    codigoAnvisa: 'CATMAT-289411',
    classeTerapeutica: 'Equipamento de Proteção Individual (EPI)',
    estoqueMinimoSugerido: 20,
    sinonimos: ['Luva de Procedimento G', 'Luva Látex G'],
  },
  {
    tipoItem: 'MATERIAL',
    nome: 'Luva Cirúrgica Estéril em Látex Par Nº 7,5',
    principioAtivo: 'Látex Natural Estéril com Punho Anatômico',
    forma: 'Par de Luvas Estéreis',
    concentracao: 'Nº 7,5',
    unidade: 'PAR',
    codigoEan: '7891058002156',
    codigoAnvisa: 'CATMAT-289425',
    classeTerapeutica: 'Procedimentos Cirúrgicos e Assépticos',
    estoqueMinimoSugerido: 50,
    sinonimos: ['Luva Cirúrgica 7,5', 'Luva Estéril 7.5'],
  },
  {
    tipoItem: 'MATERIAL',
    nome: 'Compressa de Gaze Hidrófila 7,5x7,5cm 13 Fios Pacote c/ 10 unidades',
    principioAtivo: '100% Algodão Hidrófilo Puro Estéril',
    forma: 'Compressa de Gaze Estéril 8 Dobras',
    concentracao: '7,5 cm x 7,5 cm',
    unidade: 'PCT',
    codigoEan: '7891058002163',
    codigoAnvisa: 'CATMAT-312980',
    classeTerapeutica: 'Curativo e Procedimento Cirúrgico',
    estoqueMinimoSugerido: 100,
    sinonimos: ['Gaze Estéril', 'Gaze 7,5x7,5', 'Pacote de Gaze'],
  },
  {
    tipoItem: 'MATERIAL',
    nome: 'Fita Microporosa Hipoalergênica Branca 25mm x 10m',
    principioAtivo: 'Fita Médica Não-Tecido Hipoalergênica',
    forma: 'Rolo de Fita Adesiva',
    concentracao: '25 mm x 10 m (1 polegada)',
    unidade: 'RL',
    codigoEan: '7891058002170',
    codigoAnvisa: 'CATMAT-334105',
    classeTerapeutica: 'Fixação de Curativos e Dispositivos',
    estoqueMinimoSugerido: 30,
    sinonimos: ['Micropore', 'Fita Micropore', 'Esparadrapo Microporoso'],
  },
  {
    tipoItem: 'MATERIAL',
    nome: 'Sonda Uretral Tipo Foley 2 Vias Nº 16 Fr com Balão 30mL',
    principioAtivo: 'Silicone / Látex Siliconizado Estéril',
    forma: 'Cateter Vesical de Demora',
    concentracao: '16 Fr (Balão 30 mL)',
    unidade: 'UNID',
    codigoEan: '7891058002187',
    codigoAnvisa: 'CATMAT-421908',
    classeTerapeutica: 'Sondagem Vesical de Demora (SVD)',
    estoqueMinimoSugerido: 20,
    sinonimos: ['Sonda Foley 16', 'Cateter Foley 16Fr', 'SVD 16'],
  },
  {
    tipoItem: 'MATERIAL',
    nome: 'Bolsa Coletora de Urina Sistema Fechado 2000mL com Válvula Anti-Refluxo',
    principioAtivo: 'Bolsa Coletora Graduada com Clamp e Tubo Extensor',
    forma: 'Sistema Fechado Estéril',
    concentracao: 'Capacidade 2000 mL',
    unidade: 'UNID',
    codigoEan: '7891058002194',
    codigoAnvisa: 'CATMAT-421915',
    classeTerapeutica: 'Drenagem Vesical / Urologia',
    estoqueMinimoSugerido: 30,
    sinonimos: ['Coletor Sistema Fechado', 'Bolsa Coletora de Urina', 'Coletor 2000mL'],
  },
  {
    tipoItem: 'MATERIAL',
    nome: 'Sonda Nasogástrica Tipo Levin Longa Nº 14 Fr (110cm)',
    principioAtivo: 'PVC Atóxico Cristal Flexível com Linha Radiopaca',
    forma: 'Sonda Enteral / Gástrica Estéril',
    concentracao: '14 Fr (110 cm)',
    unidade: 'UNID',
    codigoEan: '7891058002200',
    codigoAnvisa: 'CATMAT-421930',
    classeTerapeutica: 'Descompressão Gástrica e Nutrição Enteral',
    estoqueMinimoSugerido: 25,
    sinonimos: ['Sonda Levin 14', 'SNG 14', 'Sonda Nasogástrica 14Fr'],
  },
];
