/** Modelos de prescrição médica hospitalar pré-definidos baseados nos formulários oficiais */

export type ItemPrescricaoLinhaDupla = {
  tipoItem: 'LINHA_DUPLA'
  nomeMedicamento: string
  observacoes: string
  principioAtivo: string
  dose: string
  unidadeMedida: string
  via: string
  frequencia: string
}

/** Modelo 1: Prescrição Médica Ala Obstétrica (Hospital Municipal) */
export const MODELO_ALA_OBSTETRICA: ItemPrescricaoLinhaDupla[] = [
  {
    tipoItem: 'LINHA_DUPLA',
    nomeMedicamento: 'DIETA',
    observacoes: '',
    principioAtivo: '',
    dose: '',
    unidadeMedida: '',
    via: '',
    frequencia: '',
  },
  {
    tipoItem: 'LINHA_DUPLA',
    nomeMedicamento: 'HIDRATAÇÃO: - SRL 2000ml, EV 24H, + 02 AMP OCITOCINA 5UI/ 1ML EM CADA FASE DE SORO',
    observacoes: '24/24H',
    principioAtivo: '',
    dose: '',
    unidadeMedida: '',
    via: '',
    frequencia: '',
  },
  {
    tipoItem: 'LINHA_DUPLA',
    nomeMedicamento: 'ANTIBIÓTICOS: - CEFALOTINA 1G - 01 FA + 100ML, SF 0,9%, EV',
    observacoes: '06/06H',
    principioAtivo: '',
    dose: '',
    unidadeMedida: '',
    via: '',
    frequencia: '',
  },
  {
    tipoItem: 'LINHA_DUPLA',
    nomeMedicamento: 'PROFILAXIAS: - DIPIRONA 500MG/ML - 02 AMP + AD, EV S/N',
    observacoes: '06/06H S/N',
    principioAtivo: '',
    dose: '',
    unidadeMedida: '',
    via: '',
    frequencia: '',
  },
  {
    tipoItem: 'LINHA_DUPLA',
    nomeMedicamento: 'PROFILAXIAS: - CETOPROFENO 100MG + SF 0,9% 100ML - EV',
    observacoes: '12/12H',
    principioAtivo: '',
    dose: '',
    unidadeMedida: '',
    via: '',
    frequencia: '',
  },
  {
    tipoItem: 'LINHA_DUPLA',
    nomeMedicamento: 'PROFILAXIAS: - 02 AMP OCITOCINA EM CADA FASE DE SORO',
    observacoes: '',
    principioAtivo: '',
    dose: '',
    unidadeMedida: '',
    via: '',
    frequencia: '',
  },
  {
    tipoItem: 'LINHA_DUPLA',
    nomeMedicamento: 'SINTOMÁTICOS: PROMETAZINA 50MG/2ML - 01 AMP IM SE PRURIDO/ALERGIA',
    observacoes: 'SN',
    principioAtivo: '',
    dose: '',
    unidadeMedida: '',
    via: '',
    frequencia: '',
  },
  {
    tipoItem: 'LINHA_DUPLA',
    nomeMedicamento: 'SINTOMÁTICOS: - ONDANSETRONA 8 MG + AD 01 AMP EV, SE NÁUSEA OU VÔMITOS',
    observacoes: '8/8H SN',
    principioAtivo: '',
    dose: '',
    unidadeMedida: '',
    via: '',
    frequencia: '',
  },
  {
    tipoItem: 'LINHA_DUPLA',
    nomeMedicamento: 'SINTOMÁTICOS: - SF 0,9% 100 ML + TRAMADOL 100 MG/2ML + METOCLOPRAMIDA 10MG/2ML MESMO SORO EV SE DOR',
    observacoes: '12/12H SN',
    principioAtivo: '',
    dose: '',
    unidadeMedida: '',
    via: '',
    frequencia: '',
  },
  {
    tipoItem: 'LINHA_DUPLA',
    nomeMedicamento: 'CONTROLE GLICÊMICO: SE PACIENTE DIABÉTICA: HGT 6/6H; INSULINA REGULAR CONFORME HGT (<150:0UI | 151-200:2UI | 201-250:4UI | 251-300:6UI | 301-350:8UI | 351-400:10UI | >400:12UI COMUNICAR PLANTONISTA)',
    observacoes: '6/6H SN',
    principioAtivo: '',
    dose: '',
    unidadeMedida: '',
    via: '',
    frequencia: '',
  },
  {
    tipoItem: 'LINHA_DUPLA',
    nomeMedicamento: 'EQUIPE DE ENFERMAGEM: - OBSERVAR SANGRAMENTO VAGINAL E TÔNUS UTERINO',
    observacoes: 'ROTINA',
    principioAtivo: '',
    dose: '',
    unidadeMedida: '',
    via: '',
    frequencia: '',
  },
  {
    tipoItem: 'LINHA_DUPLA',
    nomeMedicamento: 'EQUIPE DE ENFERMAGEM: - SINAIS VITAIS 6/6H',
    observacoes: '6/6H',
    principioAtivo: '',
    dose: '',
    unidadeMedida: '',
    via: '',
    frequencia: '',
  },
  {
    tipoItem: 'LINHA_DUPLA',
    nomeMedicamento: 'EQUIPE DE ENFERMAGEM: - REALIZAR CURATIVOS DIÁRIOS',
    observacoes: 'DIÁRIO',
    principioAtivo: '',
    dose: '',
    unidadeMedida: '',
    via: '',
    frequencia: '',
  },
  {
    tipoItem: 'LINHA_DUPLA',
    nomeMedicamento: 'EQUIPE DE ENFERMAGEM: - RETIRAR SONDA VESICAL APÓS TÉRMINO DA HIDRATAÇÃO VENOSA',
    observacoes: 'ROTINA',
    principioAtivo: '',
    dose: '',
    unidadeMedida: '',
    via: '',
    frequencia: '',
  },
  {
    tipoItem: 'LINHA_DUPLA',
    nomeMedicamento: 'FISIOTERAPIA: - REALIZAR FISIOTERAPIA RESPIRATÓRIA E MOTORA',
    observacoes: 'ROTINA',
    principioAtivo: '',
    dose: '',
    unidadeMedida: '',
    via: '',
    frequencia: '',
  },
]

/** Modelo 2: Prescrição Médica Enfermaria Geral (Hospital Municipal) */
export const MODELO_ENFERMARIA_GERAL: ItemPrescricaoLinhaDupla[] = [
  {
    tipoItem: 'LINHA_DUPLA',
    nomeMedicamento: 'DIETA E HIDRATAÇÃO: 1. DIETA A POR',
    observacoes: 'ROTINA',
    principioAtivo: '',
    dose: '',
    unidadeMedida: '',
    via: '',
    frequencia: '',
  },
  {
    tipoItem: 'LINHA_DUPLA',
    nomeMedicamento: 'DIETA E HIDRATAÇÃO: 2. SF 0,9% - 1000ML, EV, EM 24H',
    observacoes: '24/24H',
    principioAtivo: '',
    dose: '',
    unidadeMedida: '',
    via: '',
    frequencia: '',
  },
  {
    tipoItem: 'LINHA_DUPLA',
    nomeMedicamento: 'ANTIMICROBIANOS: 3. (A definir conforme cultura / diagnóstico)',
    observacoes: '',
    principioAtivo: '',
    dose: '',
    unidadeMedida: '',
    via: '',
    frequencia: '',
  },
  {
    tipoItem: 'LINHA_DUPLA',
    nomeMedicamento: 'MEDICAÇÕES DE SUPORTE: 5. OMEPRAZOL 40MG - 01 COMP, VO',
    observacoes: '24/24H SN',
    principioAtivo: '',
    dose: '',
    unidadeMedida: '',
    via: '',
    frequencia: '',
  },
  {
    tipoItem: 'LINHA_DUPLA',
    nomeMedicamento: 'MEDICAÇÕES DE SUPORTE: 6. CAPTOPRIL 25MG SL SE PAS >= 180 OU PAD >= 110 mmHg',
    observacoes: 'SN',
    principioAtivo: '',
    dose: '',
    unidadeMedida: '',
    via: '',
    frequencia: '',
  },
  {
    tipoItem: 'LINHA_DUPLA',
    nomeMedicamento: 'MEDICAÇÕES DE SUPORTE: 7. DIPIRONA 1g/2ML - 01 FA + 10 ML AD - EV 6/6 HRS SE T > 37,8°C e/ou DOR',
    observacoes: '6/6H SN',
    principioAtivo: '',
    dose: '',
    unidadeMedida: '',
    via: '',
    frequencia: '',
  },
  {
    tipoItem: 'LINHA_DUPLA',
    nomeMedicamento: 'MEDICAÇÕES DE SUPORTE: 8. PLASIL 10 MG/2ML - 01 FA + 10 ML AD - EV 8/8 HRS SE NÁUSEAS OU VÔMITOS',
    observacoes: '8/8H SN',
    principioAtivo: '',
    dose: '',
    unidadeMedida: '',
    via: '',
    frequencia: '',
  },
  {
    tipoItem: 'LINHA_DUPLA',
    nomeMedicamento: 'MEDICAÇÕES DE SUPORTE: 9. Insulina regular conforme esquema de glicemia capilar de 6/6h (150-200:2UI | 201-250:4UI | 251-300:6UI | 351-400:10UI | >400:12UI ACM)',
    observacoes: '6/6H',
    principioAtivo: '',
    dose: '',
    unidadeMedida: '',
    via: '',
    frequencia: '',
  },
  {
    tipoItem: 'LINHA_DUPLA',
    nomeMedicamento: 'MEDICAÇÕES DE SUPORTE: 10. GLICOSE 50% 04 AMP-EV SE GLICEMIA < 70',
    observacoes: 'SN ATENÇÃO',
    principioAtivo: '',
    dose: '',
    unidadeMedida: '',
    via: '',
    frequencia: '',
  },
  {
    tipoItem: 'LINHA_DUPLA',
    nomeMedicamento: 'CUIDADOS GERAIS: 11. CCGG + SSVV',
    observacoes: 'ROTINA',
    principioAtivo: '',
    dose: '',
    unidadeMedida: '',
    via: '',
    frequencia: '',
  },
]

export const ITENS_MODELO_HOSPITALAR_PADRAO = MODELO_ENFERMARIA_GERAL
